# Generated by Django 3.0.5 on 2020-05-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='old_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
