# Generated by Django 3.0.5 on 2020-05-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
