# Generated by Django 3.0.5 on 2020-05-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='old_price',
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
