# Generated by Django 3.0.5 on 2020-05-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='old_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
