# Generated by Django 3.0.5 on 2020-05-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_item_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='old_price',
            new_name='discount_price',
        ),
    ]
