# Generated by Django 3.0.5 on 2020-05-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200514_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='user',
        ),
    ]
