# Generated by Django 3.0.5 on 2020-05-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200521_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_session',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='user_session',
        ),
    ]
