# Generated by Django 3.0.5 on 2020-05-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200521_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='Order',
            field=models.ManyToManyField(to='core.Order'),
        ),
    ]
