# Generated by Django 3.0.5 on 2020-05-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200522_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='Order',
            field=models.ManyToManyField(blank=True, to='core.Order'),
        ),
    ]
