# Generated by Django 3.0.5 on 2020-05-26 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_product_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 12, 28, 26, 155174, tzinfo=utc), verbose_name='date published'),
        ),
    ]
