# Generated by Django 3.0.5 on 2020-05-26 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200526_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 12, 31, 53, 295935, tzinfo=utc), verbose_name='date published'),
        ),
    ]
