# Generated by Django 3.0.5 on 2020-05-26 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200526_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
