# Generated by Django 3.0.5 on 2020-05-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20200528_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=55, null=True),
        ),
    ]
