# Generated by Django 3.0.5 on 2020-05-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20200529_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='custom_slug',
            field=models.SlugField(default=False),
        ),
    ]
