# Generated by Django 3.0.5 on 2020-05-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_category_custom_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='custom_slug',
            field=models.BooleanField(default=False),
        ),
    ]
