# Generated by Django 3.0.5 on 2020-05-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200529_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_slug',
            field=models.BooleanField(default=False),
        ),
    ]
