# Generated by Django 3.0.5 on 2020-05-29 18:29

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_product_custom_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
    ]
