# Generated by Django 3.0.5 on 2020-06-03 11:39

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_value', to='core.Product'),
        ),
    ]
