# Generated by Django 3.0.5 on 2020-06-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_category_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brands',
            field=models.ManyToManyField(to='core.Brand'),
        ),
    ]
