# Generated by Django 3.0.5 on 2020-06-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_category_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='category',
            name='properties',
        ),
    ]
