# Generated by Django 3.0.5 on 2020-06-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20200603_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
    ]
