# Generated by Django 3.0.5 on 2020-06-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20200605_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='custom_slug',
            field=models.BooleanField(default=False),
        ),
    ]
