# Generated by Django 3.0.5 on 2020-06-08 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20200608_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyvalue',
            options={'verbose_name': 'PropertyValue', 'verbose_name_plural': 'PropertyValues'},
        ),
    ]
