# Generated by Django 3.0.5 on 2020-06-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20200608_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvalue',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
