# Generated by Django 3.0.5 on 2020-06-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_propertyvalue_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvalue',
            name='custom_slug',
            field=models.BooleanField(default=False),
        ),
    ]
