# Generated by Django 3.0.5 on 2020-06-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20200610_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='street_adress',
            new_name='street_address',
        ),
    ]
