# Generated by Django 3.0.5 on 2020-06-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20200610_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='phone',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='postcode',
            field=models.CharField(max_length=15),
        ),
    ]
