# Generated by Django 3.0.5 on 2020-06-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20200610_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ManyToManyField(to='core.Category'),
        ),
    ]
