# Generated by Django 3.0.5 on 2020-06-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20200611_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='properties',
            field=models.ManyToManyField(to='core.Property'),
        ),
    ]
