# Generated by Django 3.0.5 on 2020-06-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_productcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductComment',
            new_name='ProductReview',
        ),
    ]
