# Generated by Django 3.0.5 on 2020-06-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_auto_20200616_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='customer_review',
            field=models.FloatField(),
        ),
    ]
