# Generated by Django 3.0.5 on 2020-06-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20200616_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
