# Generated by Django 3.0.5 on 2020-06-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20200623_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='00000001', max_length=8),
            preserve_default=False,
        ),
    ]
