# Generated by Django 3.0.5 on 2020-06-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_product_extra_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='extra_category',
        ),
    ]
