# Generated by Django 3.0.5 on 2020-06-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20200626_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_duration', models.DurationField(verbose_name='Длительность предложениия')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='Продукт')),
            ],
        ),
        migrations.DeleteModel(
            name='Test_Category',
        ),
    ]
