# Generated by Django 3.0.5 on 2020-06-30 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_auto_20200630_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotproduct',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='Продукт'),
        ),
    ]
