# Generated by Django 3.0.5 on 2020-06-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20200630_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotproduct',
            name='offer_duration',
        ),
    ]
