# Generated by Django 3.0.5 on 2020-06-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_remove_hotproduct_offer_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotproduct',
            name='offer_duration',
            field=models.DateTimeField(null=True, verbose_name='Длительность предложениия'),
        ),
    ]
