# Generated by Django 3.0.5 on 2020-06-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_hotproduct_offer_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotproduct',
            old_name='offer_duration',
            new_name='deal_end_date',
        ),
    ]
