# Generated by Django 3.0.5 on 2020-07-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_auto_20200701_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='show_on_the_homepage_at_the_footer',
            field=models.BooleanField(default=False, verbose_name='Показать в футере на главной'),
        ),
    ]
