# Generated by Django 3.0.5 on 2020-07-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_auto_20200701_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='additional_parent',
            field=models.ManyToManyField(related_name='_category_additional_parent_+', to='core.Category', verbose_name='repeated_categories'),
        ),
    ]
