# Generated by Django 3.0.5 on 2020-07-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_auto_20200701_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='additional_parents',
            field=models.ManyToManyField(help_text='Список категорий, под которыми отображать данную категорию как дочернюю.', null=True, related_name='additional_children', to='core.Category', verbose_name='Дополнительные родители'),
        ),
    ]
