# Generated by Django 3.0.5 on 2020-07-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_auto_20200701_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='additional_parents',
            field=models.ManyToManyField(help_text='Список категорий, под которыми отображать данную категорию как дочернюю.', to='core.Category', verbose_name='Дополнительные родители'),
        ),
    ]
