# Generated by Django 3.0.5 on 2020-07-02 08:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_auto_20200702_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTinyMCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
    ]
