# Generated by Django 3.0.5 on 2020-07-02 12:42

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_testclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(to='core.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='custom_slug',
            field=models.BooleanField(default=False, help_text='Поле, которое указывает, перезаписывать ли slug(строка в URL) или оставить автоматическое сохранение. Это необходимо, если категория с таким же slug уже есть, так как невозможно сохранить две и более категории с одинаковым slug. В ином случае нет необходимости вводить собственный slug', verbose_name='Собственный slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='', verbose_name='Главное изображение продукта'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_on_the_homepage_at_the_footer',
            field=models.BooleanField(default=False, verbose_name='Показать категорию в подвале на главной странице'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Строка в URL, по которой можно найти категорию. Заполняется автоматически во время сохранения страницы. Если поле "Собственный slug" включено, то необходимо вручную ввести сюда свой slug в формате: eto-moi-slug ', max_length=55, null=True, unique=True),
        ),
    ]
