# Generated by Django 3.0.5 on 2020-07-02 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0118_auto_20200702_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='customer_ip',
            field=models.CharField(max_length=50, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='customer_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='customer_review',
            field=models.FloatField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='customer_review_text',
            field=models.TextField(max_length=255, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='customer_session',
            field=models.CharField(help_text='Номер сессии это отличительный это номер сеанса пользователя', max_length=50, verbose_name='Номер сессии'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
