# Generated by Django 3.0.5 on 2020-07-02 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_auto_20200702_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Свойство товаров', 'verbose_name_plural': 'Свойства товаров'},
        ),
        migrations.AlterModelOptions(
            name='propertyvalue',
            options={'verbose_name': 'Свойство товара со значением', 'verbose_name_plural': 'Свойства товаров со значениями'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Строка в URL, по которой можно найти категорию. Заполняется автоматически во время сохранения страницы. Если поле "Собственный slug" включено, то необходимо вручную ввести сюда свой slug в формате: eto-moi-slug.', max_length=55, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Строка в URL, по которой можно найти категорию. Заполняется автоматически во время сохранения страницы. Если поле "Собственный slug" включено, то необходимо вручную ввести сюда свой slug в формате: eto-moi-slug.', null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='property',
            name='categories',
            field=models.ManyToManyField(help_text='Список категорий, к которым будет относится свойство', to='core.Category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='property',
            name='custom_slug',
            field=models.BooleanField(default=False, help_text='Поле, которое указывает, перезаписывать ли slug(строка в URL) или оставить автоматическое сохранение. Это необходимо, если категория с таким же slug уже есть, так как невозможно сохранить две и более категории с одинаковым slug. В ином случае нет необходимости вводить собственный slug.', verbose_name='Собственный slug'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=75, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, help_text='Строка в URL, по которой можно найти категорию. Заполняется автоматически во время сохранения страницы. Если поле "Собственный slug" включено, то необходимо вручную ввести сюда свой slug в формате: eto-moi-slug.', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='custom_slug',
            field=models.BooleanField(default=False, help_text='Поле, которое указывает, перезаписывать ли slug(строка в URL) или оставить автоматическое сохранение. Это необходимо, если категория с таким же slug уже есть, так как невозможно сохранить две и более категории с одинаковым slug. В ином случае нет необходимости вводить собственный slug.', verbose_name='Собственный slug'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Property', verbose_name='Свойство'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='slug',
            field=models.SlugField(blank=True, help_text='Строка в URL, по которой можно найти категорию. Заполняется автоматически во время сохранения страницы. Если поле "Собственный slug" включено, то необходимо вручную ввести сюда свой slug в формате: eto-moi-slug.', null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='value',
            field=models.CharField(max_length=55, verbose_name='Значение'),
        ),
    ]
