# Generated by Django 3.0.5 on 2020-07-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_auto_20200702_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotproduct',
            options={'verbose_name': 'Горящее предложение', 'verbose_name_plural': 'Горящие предложение'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': 'Отзыв покупателя', 'verbose_name_plural': 'Отзывы покупателей'},
        ),
    ]
