# Generated by Django 3.0.5 on 2020-07-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_auto_20200702_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='additional_parents',
            field=models.ManyToManyField(blank=True, help_text='Относится только к меню. Список категорий, под которыми отображать данную категорию как дочернюю.', to='core.Category', verbose_name='Дополнительные родители'),
        ),
        migrations.DeleteModel(
            name='TestClass',
        ),
    ]
