# Generated by Django 3.0.5 on 2020-07-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_property_range_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Список категорий, к которым будет относится свойство', to='core.Category', verbose_name='Категории'),
        ),
    ]
