# Generated by Django 3.0.5 on 2020-07-07 14:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_auto_20200707_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
    ]
