# Generated by Django 3.0.5 on 2020-07-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_auto_20200707_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, help_text='Если указана скидочная цена, она будет отражаться вместо обычной цены.', null=True, verbose_name='Скидочная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, help_text='Строка в URL, по которой можно найти категорию. Заполняется автоматически во время сохранения страницы. Если поле "Собственный slug" включено, то необходимо вручную ввести сюда свой slug в формате: eto-moi-slug.', max_length=155, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='slug',
            field=models.SlugField(blank=True, help_text='Строка в URL, по которой можно найти категорию. Заполняется автоматически во время сохранения страницы. Если поле "Собственный slug" включено, то необходимо вручную ввести сюда свой slug в формате: eto-moi-slug.', max_length=155, null=True, verbose_name='Slug'),
        ),
    ]
