# Generated by Django 3.0.5 on 2020-07-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_auto_20200708_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Строка в URL, по которой можно найти категорию. Заполняется автоматически во время сохранения страницы. Если поле "Собственный slug" включено, то необходимо вручную ввести сюда свой slug в формате: eto-moi-slug.', max_length=155, null=True, verbose_name='Slug'),
        ),
    ]
