# Generated by Django 3.0.5 on 2020-07-15 08:26

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_auto_20200708_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='', verbose_name='Изображение на баннере')),
            ],
        ),
        migrations.DeleteModel(
            name='TestTinyMCE',
        ),
    ]
