# Generated by Django 3.0.5 on 2020-07-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_auto_20200715_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagebannerimage',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
    ]
