# Generated by Django 3.0.5 on 2020-07-15 09:14

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_auto_20200715_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagebannerimage',
            name='image',
        ),
        migrations.AddField(
            model_name='homepagebannerimage',
            name='banner_image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='', verbose_name='Изображение на баннере'),
            preserve_default=False,
        ),
    ]
