# Generated by Django 3.0.5 on 2020-07-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_auto_20200715_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyvalue',
            options={'ordering': ['value'], 'verbose_name': 'Свойство товара со значением', 'verbose_name_plural': 'Свойства товара со значением'},
        ),
    ]
