# Generated by Django 3.0.5 on 2020-07-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_auto_20200717_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvalue',
            name='int_value_of_value',
            field=models.IntegerField(blank=True, help_text="Численное значение, которое берется из поля 'Значение'. Заполняется автоматически во время сохранения страницы.", null=True, verbose_name='Численное значение'),
        ),
    ]
