# Generated by Django 3.0.5 on 2020-07-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_auto_20200717_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyvalue',
            options={'ordering': ['int_value_of_value', 'value'], 'verbose_name': 'Свойство товара со значением', 'verbose_name_plural': 'Свойства товара со значением'},
        ),
    ]
