# Generated by Django 3.0.5 on 2020-07-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_auto_20200719_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_stock',
            field=models.BooleanField(default=False, help_text='Если помечено галочкой, наличие товара будет отображаться "На складах компании" ', verbose_name='На складе'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_availability',
            field=models.IntegerField(default=1, help_text='Если количество товара равно 0, товар будет помечен серым цветом.', verbose_name='Количество товара в наличии'),
            preserve_default=False,
        ),
    ]
