# Generated by Django 3.0.5 on 2020-07-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_auto_20200721_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotproduct',
            options={'verbose_name': 'Горящее предложение', 'verbose_name_plural': 'Горящие предложения'},
        ),
    ]
