# Generated by Django 3.0.5 on 2020-07-29 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_auto_20200729_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebannerimage',
            name='cattegory_follow_to',
            field=models.ForeignKey(help_text='Категория которая будет открываться при клике на баннер', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Категория'),
        ),
    ]
