# Generated by Django 3.0.5 on 2020-07-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_homepagebannerimage_cattegory_follow_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagebannerimage',
            old_name='cattegory_follow_to',
            new_name='category_follow_to',
        ),
    ]
