# Generated by Django 3.0.5 on 2020-07-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_auto_20200729_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='published',
            field=models.BooleanField(default=False, help_text='Показывать ли этот отзыв на странице с продуктом.', verbose_name='Опубликовать'),
        ),
    ]
