# Generated by Django 3.0.5 on 2020-08-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_productreview_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='', help_text='Текст отоброжающийся внизу страницы категории', verbose_name='Описание категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_title',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Page title'),
        ),
    ]
