# Generated by Django 3.0.5 on 2020-08-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_auto_20200811_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Текст отоброжающийся внизу страницы категории', null=True, verbose_name='Описание категории'),
        ),
    ]
