# Generated by Django 3.0.5 on 2020-08-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_customerrequesttocallback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerRequestToCallBack',
        ),
    ]
