# Generated by Django 3.0.5 on 2020-08-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_auto_20200817_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerrequesttocallback',
            options={'verbose_name': 'Запрос на звонок', 'verbose_name_plural': 'Запросы на звонок'},
        ),
        migrations.AlterField(
            model_name='customerrequesttocallback',
            name='customer_called_back',
            field=models.BooleanField(default=False, verbose_name='Клиенту перезвонили?'),
        ),
        migrations.AlterField(
            model_name='customerrequesttocallback',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
    ]
