# Generated by Django 3.0.6 on 2020-08-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_auto_20200817_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count_delievery_cost_for_each_product',
            field=models.BooleanField(default=False, verbose_name='Считать доставку за каждый товар'),
        ),
        migrations.AddField(
            model_name='category',
            name='delievery_cost',
            field=models.IntegerField(default=0, verbose_name='Цена за доставку товара'),
        ),
    ]
