# Generated by Django 3.0.6 on 2020-08-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_auto_20200825_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelieveryPaymentOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название способа оплаты')),
                ('description', models.CharField(max_length=355, verbose_name='Описание способа оплаты')),
                ('slug', models.SlugField(max_length=35, verbose_name='Slug')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='delievery_cost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена за доставку товара'),
        ),
    ]
