# Generated by Django 3.0.6 on 2020-08-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_auto_20200825_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelieveryCityOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название города')),
                ('slug', models.SlugField(max_length=25, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Доступный для доставки город',
                'verbose_name_plural': 'Доступные для доставки города',
            },
        ),
        migrations.CreateModel(
            name='DelieveryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название способа доставки')),
                ('description', models.CharField(max_length=355, verbose_name='Описание способа доставки')),
                ('slug', models.SlugField(max_length=55, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Способы доставки',
            },
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название способа оплаты')),
                ('description', models.CharField(max_length=355, verbose_name='Описание способа оплаты')),
                ('slug', models.SlugField(max_length=35, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.DeleteModel(
            name='DelieveryPaymentOption',
        ),
    ]
