# Generated by Django 3.0.6 on 2020-08-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_auto_20200827_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='city_address',
            field=models.CharField(max_length=25, verbose_name='Город'),
        ),
    ]
