# Generated by Django 3.0.6 on 2020-08-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_auto_20200827_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='delievery_option',
            field=models.CharField(default='', max_length=55, verbose_name='Способ доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='payment_option',
            field=models.CharField(default='', max_length=55, verbose_name='Способ оплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delieveryoption',
            name='slug',
            field=models.SlugField(blank=True, max_length=55, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='slug',
            field=models.SlugField(blank=True, max_length=35, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
