# Generated by Django 3.0.6 on 2020-08-31 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_auto_20200829_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='delievery_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DelieveryOption', verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='payment_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PaymentOption', verbose_name='Способ оплаты'),
        ),
    ]
