# Generated by Django 3.0.6 on 2020-08-31 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_auto_20200831_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='city_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DelieveryCityOption', verbose_name='Город'),
        ),
    ]
