# Generated by Django 3.0.6 on 2020-09-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_auto_20200831_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='first_name',
            new_name='customer_first_name',
        ),
    ]
