# Generated by Django 3.0.6 on 2020-09-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_auto_20200901_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedbasket',
            name='credit_duration',
            field=models.IntegerField(null=True, verbose_name='Количество месяцев для кредита'),
        ),
        migrations.AddField(
            model_name='orderedbasket',
            name='credit_month_payment',
            field=models.IntegerField(null=True, verbose_name='Стоимость ежемесячного взноса'),
        ),
        migrations.AddField(
            model_name='orderedbasket',
            name='customer_wants_credit',
            field=models.BooleanField(default=False, null=True, verbose_name='Покупатель оформил в кредит'),
        ),
        migrations.AddField(
            model_name='orderedbasket',
            name='total_summary',
            field=models.IntegerField(null=True, verbose_name='Общая стоимость'),
        ),
    ]
