# Generated by Django 3.0.6 on 2020-09-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_auto_20200902_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedbasket',
            name='credit_duration',
            field=models.IntegerField(verbose_name='Количество месяцев для кредита'),
        ),
        migrations.AlterField(
            model_name='orderedbasket',
            name='credit_month_payment',
            field=models.IntegerField(verbose_name='Стоимость ежемесячного взноса'),
        ),
    ]
