# Generated by Django 3.0.6 on 2020-09-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_auto_20200902_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedbasket',
            name='customer_wants_credit',
            field=models.BooleanField(default=False, verbose_name='Покупатель оформил в кредит'),
        ),
        migrations.AlterField(
            model_name='orderedbasket',
            name='total_summary',
            field=models.IntegerField(verbose_name='Общая стоимость'),
        ),
    ]
