# Generated by Django 3.0.6 on 2020-09-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_auto_20200902_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedbasket',
            name='credit_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество месяцев для кредита'),
        ),
        migrations.AlterField(
            model_name='orderedbasket',
            name='credit_month_payment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость ежемесячного взноса'),
        ),
    ]
