# Generated by Django 3.0.6 on 2020-09-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_auto_20200902_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basket_changed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата изменения корзины'),
        ),
    ]
