# Generated by Django 3.0.6 on 2020-09-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_basket_basket_changed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedbasket',
            name='delievery_payment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='orderedbasket',
            name='total_summary',
            field=models.IntegerField(verbose_name='Общая стоимость корзины'),
        ),
    ]
