# Generated by Django 3.0.6 on 2020-09-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_auto_20200902_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='delieverycityoption',
            name='custom_slug',
            field=models.BooleanField(default=False, verbose_name='Собственный Slug'),
        ),
        migrations.AddField(
            model_name='delieveryoption',
            name='custom_slug',
            field=models.BooleanField(default=False, verbose_name='Собственный Slug'),
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='custom_slug',
            field=models.BooleanField(default=False, verbose_name='Собственный Slug'),
        ),
    ]
