# Generated by Django 3.0.6 on 2020-09-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_auto_20200902_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_in_dollars',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена в долларах'),
        ),
    ]
