# Generated by Django 3.0.6 on 2020-09-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_product_price_in_dollars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvalue',
            name='int_value_of_value',
            field=models.FloatField(blank=True, help_text="Численное значение, которое берется из поля 'Значение'. Заполняется автоматически во время сохранения страницы.", null=True, verbose_name='Численное значение'),
        ),
    ]
