# Generated by Django 3.0.6 on 2020-09-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_auto_20200922_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='dynamic_seo',
            field=models.BooleanField(default=False, help_text='Автоматически вставлять свойство в title и description при фильтрации категорий.', verbose_name='Динамическое SEO в категориях'),
        ),
        migrations.AlterField(
            model_name='property',
            name='weight',
            field=models.IntegerField(help_text='Чем выше вес свойства, тем выше оно будет в списке фильтров и в списке свойств на страницах товаров ', verbose_name='Вес категории'),
        ),
    ]
