# Generated by Django 3.0.6 on 2020-09-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_auto_20200924_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='where_to_insert_dynamic_meta_description_data',
            field=models.IntegerField(blank=True, help_text='После какого слова в description вставлять динамические свойства', null=True, verbose_name='Местоположение динамеческих свойств в description'),
        ),
        migrations.AddField(
            model_name='category',
            name='where_to_insert_dynamic_page_title_data',
            field=models.IntegerField(blank=True, help_text='После какого слова в title вставлять динамические свойства', null=True, verbose_name='Местоположение динамеческих свойств в title'),
        ),
    ]
