# Generated by Django 3.0.6 on 2020-09-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'SEO страницы', 'verbose_name_plural': 'SEO страниц'},
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_title',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Title страницы'),
        ),
    ]
