# Generated by Django 3.0.6 on 2020-09-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(help_text='Slug - текст в адресе страницы после tehnomall.md например slug для "Контакты": /kontakti ', max_length=30, verbose_name='Slug страницы'),
        ),
    ]
