# Generated by Django 3.0.6 on 2020-10-06 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_auto_20200929_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название дополнительной опции')),
                ('slug', models.SlugField(max_length=55, verbose_name='Slug дополнительной опции')),
                ('cost', models.IntegerField(verbose_name='Стоимость дополнительной опции')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Категория дополнительной опции')),
            ],
        ),
    ]
