# Generated by Django 3.0.6 on 2020-10-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_extraoption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraoption',
            options={'verbose_name': 'Дополнительная опция', 'verbose_name_plural': 'Дополнительные опции'},
        ),
        migrations.RemoveField(
            model_name='extraoption',
            name='category',
        ),
        migrations.AddField(
            model_name='extraoption',
            name='categories',
            field=models.ManyToManyField(to='core.Category', verbose_name='Категории дополнительной опции'),
        ),
    ]
