# Generated by Django 3.0.6 on 2020-10-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0189_auto_20201006_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraoption',
            name='custom_slug',
            field=models.BooleanField(default=False, help_text='Поле, которое указывает, перезаписывать ли slug(строка в URL) или оставить автоматическое сохранение. Это необходимо, если категория с таким же slug уже есть, так как невозможно сохранить две и более категории с одинаковым slug. В ином случае нет необходимости вводить собственный slug.', verbose_name='Собственный slug'),
        ),
        migrations.AlterField(
            model_name='extraoption',
            name='slug',
            field=models.SlugField(blank=True, max_length=55, null=True, verbose_name='Slug дополнительной опции'),
        ),
    ]
