# Generated by Django 3.0.6 on 2020-10-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_auto_20201006_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraoption',
            name='categories',
        ),
    ]
