# Generated by Django 3.0.6 on 2020-10-06 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0193_extraoption_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraOptionOrdered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название опции')),
                ('slug', models.SlugField(blank=True, max_length=55, null=True, verbose_name='Slug опции')),
                ('custom_slug', models.BooleanField(default=False, help_text='Поле, которое указывает, перезаписывать ли slug(строка в URL) или оставить автоматическое сохранение. Это необходимо, если категория с таким же slug уже есть, так как невозможно сохранить две и более категории с одинаковым slug. В ином случае нет необходимости вводить собственный slug.', verbose_name='Собственный slug')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ExtraOption', verbose_name='Опция')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказанная опция для продукта',
                'verbose_name_plural': 'Заказанные опции для продуктов',
            },
        ),
        migrations.DeleteModel(
            name='TestClass',
        ),
    ]
