# Generated by Django 3.0.6 on 2020-10-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_auto_20201008_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraoptionordered',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость опции'),
            preserve_default=False,
        ),
    ]
