# Generated by Django 3.0.6 on 2020-10-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0200_auto_20201022_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_in_dollars',
            field=models.FloatField(default=1, verbose_name='Цена в долларах'),
            preserve_default=False,
        ),
    ]
