# Generated by Django 3.0.5 on 2020-07-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReduceProcentPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduce_procent', models.IntegerField(help_text='Уменьшить цену всех продуктов на n-ое кол-во процентов.', verbose_name='Кол-во %')),
            ],
            options={
                'verbose_name': 'Уменьшить цену продуктов',
            },
        ),
    ]
